/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout-complete'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResultRouteImport } from './routes/result'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan.index'
import { Route as AuthenticatedPlanDayRouteImport } from './routes/_authenticated/plan.$day'
import { Route as ApiPublicEmailsDailyRouteImport } from './routes/api/public/emails/daily'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/checkout-complete',
  path: '/checkout-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanDayRoute = AuthenticatedPlanDayRouteImport.update({
  id: '/plan/$day',
  path: '/plan/$day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicEmailsDailyRoute = ApiPublicEmailsDailyRouteImport.update({
  id: '/api/public/emails/daily',
  path: '/api/public/emails/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-complete': typeof CheckoutCompleteRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/plan/$day': typeof AuthenticatedPlanDayRoute
  '/plan/': typeof AuthenticatedPlanIndexRoute
  '/api/public/emails/daily': typeof ApiPublicEmailsDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-complete': typeof CheckoutCompleteRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/plan/$day': typeof AuthenticatedPlanDayRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/api/public/emails/daily': typeof ApiPublicEmailsDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-complete': typeof CheckoutCompleteRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/plan/$day': typeof AuthenticatedPlanDayRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/api/public/emails/daily': typeof ApiPublicEmailsDailyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/checkout-complete'
    | '/quiz'
    | '/result'
    | '/unsubscribe'
    | '/notes'
    | '/plan/$day'
    | '/plan/'
    | '/api/public/emails/daily'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/checkout-complete'
    | '/quiz'
    | '/result'
    | '/unsubscribe'
    | '/notes'
    | '/plan/$day'
    | '/plan'
    | '/api/public/emails/daily'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/checkout-complete'
    | '/quiz'
    | '/result'
    | '/unsubscribe'
    | '/_authenticated/notes'
    | '/_authenticated/plan/$day'
    | '/_authenticated/plan/'
    | '/api/public/emails/daily'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  QuizRoute: typeof QuizRoute
  ResultRoute: typeof ResultRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiPublicEmailsDailyRoute: typeof ApiPublicEmailsDailyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-complete': {
      id: '/checkout-complete'
      path: '/checkout-complete'
      fullPath: '/checkout-complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/$day': {
      id: '/_authenticated/plan/$day'
      path: '/plan/$day'
      fullPath: '/plan/$day'
      preLoaderRoute: typeof AuthenticatedPlanDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/emails/daily': {
      id: '/api/public/emails/daily'
      path: '/api/public/emails/daily'
      fullPath: '/api/public/emails/daily'
      preLoaderRoute: typeof ApiPublicEmailsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPlanDayRoute: typeof AuthenticatedPlanDayRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPlanDayRoute: AuthenticatedPlanDayRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  QuizRoute: QuizRoute,
  ResultRoute: ResultRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiPublicEmailsDailyRoute: ApiPublicEmailsDailyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
