// This file is automatically generated. Do not edit it directly.
//
// MANUAL FIX (see /quiz hydration-race dead-tap bug): the `supabase` import
// below was static (`import { supabase } from './client'`). This middleware
// is registered globally in src/start.ts, which every route's client entry
// loads, so a static import here put the whole Supabase JS SDK on the
// initial script list for "/quiz" and every other page. That directly
// widened the first-paint -> hydrated window on the one screen where a
// dropped first tap costs the most. If this file gets regenerated, redo
// this: keep `import('./client')` dynamic, inside the callback, not at
// module top-level.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
